### ISSUE TITLE
Improvement for terms/dropout.md

### ISSUE THREAD

**Issue by lowdensh** [machine-learning-glossary/glossary#28]
# Referencing file [terms/dropout.md](https://github.com/machine-learning-glossary/glossary/edit/master/terms/dropout.md)

The following link in the references is incorrect:
Dropout (neural networks) - Wikipedia (en.wikipedia.org)

It's just missing a bracket at the end. The page it leads to does suggest the correct page.

**Comment by jamesmishra** [comment]
Thank you for filing the issue! I have fixed the link.
