### ISSUE TITLE
Improvement for terms/bag-of-n-grams.md

### ISSUE THREAD

**Issue by TomConlin** [machine-learning-glossary/glossary#34]
# Referencing file [terms/bag-of-n-grams.md](https://github.com/machine-learning-glossary/glossary/edit/master/terms/bag-of-n-grams.md)

(Describe your issue here)

example is missing "best person"  2-gram from bag

**Comment by jamesmishra** [comment]
Thank you for reporting the issue. I fixed it in 855f710d47c5146b2f0a235a9361f8d2bc9dd8f9.
