### ISSUE TITLE
Improvement for terms/mean-reciprocal-rank-mrr.md

### ISSUE THREAD

**Issue by ESaiDheeraj** [machine-learning-glossary/glossary#44]
# Referencing file [terms/mean-reciprocal-rank-mrr.md](https://github.com/machine-learning-glossary/glossary/edit/master/terms/mean-reciprocal-rank-mrr.md)

(Describe your issue here)

The first link in references is currently not pointing to the Question Answering chapter. It is pointing to Phonetics chapter.

I think this [link](https://web.stanford.edu/~jurafsky/slp3/14.pdf) is pointing to Question Answering chapter. The entire chapter list can found [here](https://web.stanford.edu/~jurafsky/slp3/).

You can verify and correct it.

**Comment by jamesmishra** [comment]
Thank you for noticing! It looks like they reorganized the chapters in the draft version of SLP3. I have added a commit that fixes the reference.
